// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzsfvtrbfrfnvamjlmfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6c2Z2dHJiZnJmbnZhbWpsbWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTc0MDMsImV4cCI6MjA3MDc3MzQwM30._g4c9Oad3hnGJHOmIIzeIhAy1u1SZDhHwpPBuGnONDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});